config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  # create
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  # read one task
  get "tasks/:id", to: "tasks#show"
  # edit
  get "tasks/:id/edit", to: "tasks#edit", as:"edit_task"
  patch "tasks/:id", to: "tasks#update" , as:"task"
  # delete
  delete "tasks/:id", to: "tasks#destroy" ,as:""
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show, :edit, :update, :destroy]
	def index
		@tasks = Task.all	
	end
	def show
		@task = Task.find(params[:id])
	end
	def new
		@task = Task.new
	end
	def create
		@task = Task.new(task_params)
		@task.save
		redirect_to tasks_path(@task)
	end
	def edit
		@task = Task.find(params[:id])
	end
	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
    	redirect_to tasks_path(@task)
	end
	def destroy
		@task = Task.find(params[:id])
		@task.destroy
    	redirect_to tasks_path(@task)
	end

	private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
  	@task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsTaskManager</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
  <div class="container">
    <div class="row">
    	<div class="col">
      		<%= yield %>
    	</div>
    </div>
  </div>
</body>

</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>


<%= form_for(@task) do |f| %>

<div class="form-group ">
  <%= label_tag :checkbox, "" %>
  <%= check_box_tag("title", "value", false, class: "checkbox") %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group align-self-center">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<%= f.submit class: 'btn btn-primary align-self-center' %>

<% end %>

<%= link_to "Destroy #{@task.title}", tasks_path(@task), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/tasks/index.html.erb
  <h1>ALL TASKS</h1>

<% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task) %></h2>
  <p><%= task.details %></p>
  
  <%= link_to "Delete #{task.title}", task_path(task), method: :delete, data: { confirm: "Are you sure?"} %>
<% end %>

app/views/tasks/new.html.erb
<div class="container">
	<div class="row">

<%= form_for(@task) do |f| %>

<div class="form-group ">
  <%= label_tag :checkbox, "" %>
  <%= check_box_tag("title", "value", false, class: "checkbox") %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group align-self-center">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<%= f.submit class: 'btn btn-primary align-self-center' %>
</div>
</div>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<%= link_to "Edit the task", edit_task_path(@task) %>
<%= link_to "Back to all tasks", tasks_path %>